// Generated by https://quicktype.io

import { Room } from "./room";

export interface Customer {
    id:           number;
    roomNo:       number;
    cName:        string;
    address:      string;
    phone:        string;
    email:        string;
    checkIn:      string;
    totalPersons: number;
    bookingDays:  number;
    advance:      number;
    room:         Room;
}

