// Generated by https://quicktype.io

export interface Room {
    id:       number;
    rtCode:   number;
    status:   boolean;
    services: Service[];
}

export interface Service {
    id:          number;
    roomNo:      number;
    sDesc:       string;
    amount:      number;
    serviceDate: string;
}
